project:
  type: website
  output-dir: docs

website:
  title: "Yingyi Guo Portfolio"
  navbar:
    left:
      - text: "About You"
        href: index.qmd#about
      - text: "Projects"
        href: index.qmd#projects
      - text: "CV"
        href: index.qmd#cv
      - text: "Contact"
        href: index.qmd#contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false