project:
  type: website
  output-dir: docs

website:
  title: "Yingyi Guo Portfolio"
  navbar:
    left:
      - text: "About"
        href: "#about"
      - text: "Projects"
        href: "#projects"
      - text: "CV"
        href: "#cv"
      - text: "Contact"
        href: "#contact"

format:
  html:
    theme: cosmo
    css: styles.css