project:
  type: website
  output-dir: docs

website:
  title: "Yingyi Guo Portfolio"
  navbar:
    left:    
      - text: "Projects"
        href: projects.qmd       
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css